// File generated by FlutterFire CLI.
// This file is used to configure Firebase from dart code
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

// Replace with actual values generated by Firebase CLI
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATrMzePswg9NCFZvsenn-P_Cp-dd3dVQs',
    appId: '1:1028174393649:web:94c0ef5d5bb18cef038010',
    messagingSenderId: '1028174393649',
    projectId: 'caption-learn-2f9e3',
    authDomain: 'caption-learn-2f9e3.firebaseapp.com',
    storageBucket: 'caption-learn-2f9e3.firebasestorage.app',
    measurementId: 'G-J7C3PCJ50R',
  );

  // Replace these with your actual Firebase configuration values

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3G8ddhhUXUWK4EYtVmG16vHTKdJ8YjX8',
    appId: '1:1028174393649:android:1f20f9bf826e50ff038010',
    messagingSenderId: '1028174393649',
    projectId: 'caption-learn-2f9e3',
    storageBucket: 'caption-learn-2f9e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-XnQ0dp3seMIavxc376o7MW6rDUsnm8E',
    appId: '1:1028174393649:ios:24bf30ae7ddaf73b038010',
    messagingSenderId: '1028174393649',
    projectId: 'caption-learn-2f9e3',
    storageBucket: 'caption-learn-2f9e3.firebasestorage.app',
    iosClientId: '1028174393649-3cu65svme7gqnjb847fkeid9te7jrlgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.captionLearn',
  );

}